[project]
name = "comfyui-random-image"
description = "LoadImage-like nodes with random / sequential selection - from a local directory or from a booru tag search."
version = "0.4.0"
license = { text = "MIT License" }

[project.urls]
Repository = "https://github.com/bartenevve/comfyui-random-imageload-node"

[tool.comfy]
PublisherId = "bartenevve"
DisplayName = "Load Random Image"
Icon = ""
